version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      timezone: "-03:00 UTC"
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
