[workspace]
default-members = [
  "common",
  "server",
  "cli",
  "web-runtime",
  "runtime",
]
members = [
  "common",
  "server",
  "cli",
  "web-runtime",
  "runtime",
  "benchmarks",
  "xtask"
]
